name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    install-deps:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup

    audit:
        name: Audit vulnerabilities
        runs-on: ubuntu-latest
        needs: [ install-deps ]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup
            - run: pnpm audit --audit-level=high

    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs: [ install-deps ]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup
            - run: pnpm lint

    format-check:
        name: Format check
        runs-on: ubuntu-latest
        needs: [ install-deps ]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup
            - run: pnpm format:check

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [ install-deps ]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup
            - run: pnpm test

    build:
        name: Build extension
        runs-on: ubuntu-latest
        needs: [ lint, format-check, test ]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/job-setup
            - run: |
                  echo "Building Chrome MV3 target..."
                  pnpm build
                  echo "Building process was successful!"
            - run: |
                  echo "Building Firefox MV2 target..."
                  pnpm build:firefox
                  echo "Building process was successful!"
            - uses: actions/upload-artifact@v7
              id: upload-chrome-build-result
              with:
                  name: extension-chrome-mv3
                  path: .output/chrome-mv3/
                  retention-days: 7
                  overwrite: true
            - uses: actions/upload-artifact@v7
              id: upload-firefox-build-result
              with:
                  name: extension-firefox-mv2
                  path: .output/firefox-mv2/
                  retention-days: 7
                  overwrite: true
            - run: |
                  echo "Build artifact for chrome can be found in ${{ steps.upload-chrome-build-result.outputs.artifact-url }}."
                  echo "Build artifact for firefox can be found in ${{ steps.upload-firefox-build-result.outputs.artifact-url }}."
